### ISSUE TITLE
the resource simplyscala.com doesn't exist anymore

### ISSUE THREAD

**Issue by behrtam** [exercism/xscala#103]
The resource [simplyscala.com](http://www.simplyscala.com) listed in [docs/RESOURCES.md](https://github.com/exercism/xscala/blob/master/docs/RESOURCES.md) doesn't exist anymore. Based on this [reddit thread](https://www.reddit.com/r/scala/comments/3didyu/where_is_simplyscala_gone/) it might already been gone for at least ~6 months.

**Comment by kytrinyx** [comment]
Ah, yepp. We should remove that.
