### ISSUE TITLE
broken help link in SETUP.md

### ISSUE THREAD

**Issue by behrtam** [exercism/xscala#104]
The help pages got moved as a result the link (http://help.exercism.io/getting-started-with-scala.html) in the [SETUP.md](https://github.com/exercism/xscala/blob/master/SETUP.md) (which is included in the generated README for every exercise) is broken. I guess the new link is: http://exercism.io/languages/scala

**Comment by kytrinyx** [comment]
Yepp, that's the correct link. Fixing that now.
