### ISSUE TITLE
pangram: tests not pending

### ISSUE THREAD

**Issue by Cohen-Carlisle** [exercism/xscala#131]
@Trevoke reported:
> Just pulled the pangram exercise for Scala and no tests are pending.

**Comment by ricemery** [comment]
What does this mean? Does this refer to the fact that none of the tests are marked to be ignored?

**Comment by Trevoke** [comment]
Yes. The standard in exercism is to have the first test run and the other tests marked pending so they don't muddy up the test output, letting the user decide when to start running each test. This exercise does not follow this.

**Comment by ricemery** [comment]
This is a bigger problem than just the Pangram exercise. The majority of the Scala exercises do not use the "pending" scheme. It looks like all the exercises from "hello-world" to "gigasecond" use pending. Then all the rest do not use pending. About 46 exercises will need to be updated.

So, addressing this issue will take some time.

Thanks.

**Comment by Trevoke** [comment]
I'm going to open a new issue that reflects the situation better and has a list of unfixed exercises. Please close this one.
