### ISSUE TITLE
Exercises do not provide a named file for the code to be delivered

### ISSUE THREAD

**Issue by Trevoke** [exercism/xscala#137]
In other tracks, there is a file that people can use to write their code (whether `bob.el` or `bob.rb` or `bob.ex`). In the Scala track, currently, that file does not exist, so we have to guess what the file name is supposed to be.

This issue tracks the exercises that still need to be updated. No checkmark means the exercise still needs to be updated.
- [ ] Hello World
- [x] Bob
- [ ] Hamming
- [ ] Word Count
- [x] Pangram
- [ ] Anagram
- [ ] Nucleotide Count
- [ ] Phone Number
- [x] Grade School
- [ ] Robot Name
- [ ] Leap
- [ ] Etl
- [ ] Meetup
- [x] Space Age
- [ ] Grains
- [x] Gigasecond
- [ ] Scrabble Score
- [x] Difference Of Squares
- [x] Accumulate
- [ ] Sublist
- [ ] Rna Transcription
- [ ] Triangle
- [ ] Binary
- [ ] Roman Numerals
- [ ] Prime Factors
- [x] Raindrops
- [x] Allergies
- [x] Atbash Cipher
- [x] Bank Account
- [x] Crypto Square
- [ ] Kindergarten Garden
- [ ] Robot Simulator
- [x] Queen Attack
- [ ] Binary Search Tree
- [ ] Hexadecimal
- [ ] Largest Series Product
- [ ] Luhn
- [ ] Clock
- [ ] Matrix
- [ ] House
- [ ] Minesweeper
- [ ] Ocr Numbers
- [ ] Octal
- [ ] Trinary
- [ ] Wordy
- [ ] Food Chain
- [ ] Linked List
- [ ] Custom Set
- [ ] Nth Prime
- [ ] Palindrome Products
- [ ] Pascals Triangle
- [ ] Pig Latin
- [ ] Pythagorean Triplet
- [ ] Saddle Points
- [ ] Say
- [ ] Secret Handshake
- [ ] Series
- [ ] Sieve
- [ ] Simple Cipher
- [ ] Connect
- [x] Parallel Letter Frequency
- [x] Acronym
- [x] Forth

**Comment by ricemery** [comment]
It doesn't necessarily matter what the class file is named. If the user wants the class file named to match the class used by the tests, then this is easy enough to deduce from the tests. 
Unless we include stubbed out classes and objects, the user is going to have to figure out the class name from the tests anyways.

I'm not necessarily against having an empty class file for the user. But, it seems like a bunch of unnecessary work to me.
BTW: Having the empty file to fill out is not standardized across all the tracks. I have been working through the Rust track. There are not empty files for the Rust solutions.

**Comment by Trevoke** [comment]
I was under the impression that exercism required a particular file name for recognizing submissions. Is that not the case?

**Comment by ricemery** [comment]
Not to my knowledge. The exercism command line takes the filename as a param.

`exercism submit filename`

**Comment by Trevoke** [comment]
You're right, I'm wrong, it just depends on the provided root directory name for the exercise. So this is just a matter of convenience for the end user.

**Comment by abo64** [comment]
Part of the fun can be to figure out the types and signatures.
But especially for beginners this might be too demanding. So maybe have them added?

**Comment by ErikSchierboom** [comment]
Well, the way the Elm track does it, is by only providing an empty implementation file (albeit with a module definition on top). As @abo64 said, people should be able to figure out the types and signatures themselves, unless we want to guide them towards taking a specific path of course. So what about having empty files? Or maybe even better, use the `???` placeholder for the first few exercises to help people get started. E.g. the `bob` exercise could have a default file with the following contents:

```scala
object Bob {
  def hey(statement: String): String = ???
}
```

That way we can gradually ease users into learning Scala, and when the user has done a few exercises, we no longer provide a default implementation.

**Comment by abo64** [comment]
Sounds good to me, @ErikSchierboom 
Perhaps let's make it a rule then that if we provide such a non-empty file we always add some comment about it in the exercise's `HINTS.md` similar to the Haskell track?

**Comment by ErikSchierboom** [comment]
That seems like a very good idea! The ecmascript track also added some comments to the code:

```javascript
//
// This is only a SKELETON file for the 'Bob' exercise. It's been provided as a
// convenience to get you started writing code faster.
//

class Bob {
  hey(message) {
    //
    // YOUR CODE GOES HERE
    //
  }
}

export default Bob;
```

I wonder if we should do both. Do people always read the README fully? Sometimes I don't, and I just look at the tests.

**Comment by abo64** [comment]
Yeah, why not.  
But here is a fun fact: The Haskell guys decided to not include any comments into the code, partially as an educational measure to force people to read the READMEs.
Question is whether this really works out. :-)

**Comment by ErikSchierboom** [comment]
I am away bit skeptic about that 😀 I think we should only add the comments in code in the first exercise. Then the next couple of exercises could have only a stub implementation file.

**Comment by rbasso** [comment]
> The Haskell guys decided to not include any comments into the code, partially as an educational measure to force people to read the READMEs.
> Question is whether this really works out. :-)

I'm pretty sure most people don't read the README at first @abo64, but maybe they do after suffering for a while. :grin:

At first we used comments @ErikSchierboom, but the users - surprisingly - where not removing them before submitting. It was so frequent that started to be annoying to review the solutions. I really don't understand people...

**Comment by ErikSchierboom** [comment]
Hmmm, I think @rbasso has a point. The ecmascript track also has comments in the code, and a quick sample showed that around half of the people still had the comments in their code when they submitted. Perhaps we should then not put the comments in code, but only provide the stub implementation.

**Comment by abo64** [comment]
@ricemery As you may have noticed I merged your recent PRs.

But now I have second thoughts: What is the final decision on this issue? Shall we really provide such a file  for all exercises, or only for the first ones to help beginners? (see discussion on Nov 24 above).
(in case of the latter let's update the list of exercises).

**Comment by ErikSchierboom** [comment]
In an earlier post, I summarized my opinion as follows:

> As @abo64 said, people should be able to figure out the types and signatures themselves, unless we want to guide them towards taking a specific path of course. So what about having empty files? Or maybe even better, use the ??? placeholder for the first few exercises to help people get started. 

I think there are three options:

1. Don't provide any default file.
2. Provide an empty file.
3. Provide a file with the expected functions but without an implementation

My personal preference is to do number 3 for the first 5-10 exercises. For the remaining exercises, the question then becomes: is an empty file actually useful? For me, it kind of depends on what the IDE does with the empty file. I use IntelliJ as my editor, and when I open a test file and ask the IDE to scaffold a stub implementation, will it use the empty file? If not, will it show the empty file?

**Comment by ricemery** [comment]
@abo64 - sorry. Reading through this issue again, I realize that we never did make a final decision. 

My personal opinion is that the user should be able to figure out the signatures from the unit tests. Though it does interest me that the Haskell track is doing number 3 for all the exercises.

If we are voting, I would vote for #3 for the first 10 exercises. And, then not include any file for the remaining exercises.

**Comment by Trevoke** [comment]
I think providing an empty file is a nice convenience. Scala is a bit like
Perl in the sense that there's more than one way to do it, so providing a
skeleton might be a bad idea. We should probably only provide a skeleton if
there's an idea which we think people should explore over other ideas.

**Comment by abo64** [comment]
I go with @ErikSchierboom : `3.` for the first 10 exercises, and have an empty file for the others if the major IDEs can deal with it.
I did a quick test with my Eclipse Mars edition, and it seems to be fine: I get the expected compilation errors due to a missing implementation.

**Comment by ricemery** [comment]
I just tried an empty file with the latest and greatest IntelliJ. IntelliJ deals with the empty file just fine. In fact, the file gets ignored if a different file is used for the solution source..

**Comment by ErikSchierboom** [comment]
@ricemery Great work @ricemery. I've updated the starting comment to reflect the recently merged changes.

**Comment by ricemery** [comment]
Should we close this issue? 
Or, should we remove any interface definitions that have been checked in for the exercises that are past the first 10?

**Comment by abo64** [comment]
I think we can be relaxed here and just keep the ones past the first ten.

**Comment by ErikSchierboom** [comment]
Agreed
