### ISSUE TITLE
Change exercise does not have a main/scala directory

### ISSUE THREAD

**Issue by ricemery** [exercism/xscala#146]
Change exercise does not have a main/scala directory

**Comment by Trevoke** [comment]
I think this is the same issue as #137 ? (or part of it anyway)

**Comment by ricemery** [comment]
Yes and no. In the Scala track a ".keep" file has been used within the src/main/scala directory to make sure the user doesn't have to create src/main/scala by hand. 

You are correct in that if #137 was addressed then the .keep files would not be needed. 

Best Regards,
Ric
