### ISSUE TITLE
Configure Travis CI build

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xscala#2]
@sgrif  I'm in the process of extracting all the exercises, putting each language in its own repository.

I'm creating a separate api (http://github.com/exercism/x-api) which includes all the language repositories as git submodules.

Do you have time to set up the Travis build for the scala repository?

**Comment by nlochschmidt** [comment]
@sgrif @kytrinyx what is left to do here? Maybe I can jump in

**Comment by kytrinyx** [comment]
Oh, cool! Right now several languages run the current test suites against the example solutions on Travis-CI. Some languages also run linters and things like that.

Currently the build for the Scala track simply sanity-checks the configuration, which basically makes sure that all the exercises are listed in the config, and that they all have example solutions.

It would be great to get CI running the actual test suites against the example solutions.

For some ideas how other tracks have done it, check out
- [haskell](https://github.com/exercism/xhaskell/blob/master/.travis.yml#L5) (lots of custom bootstrapping stuff)
- [ruby](https://github.com/exercism/xruby/blob/master/.travis.yml#L15) (copies the tests into a tmp dir, renames the example solution, deletes 'skips' from the tests, then runs the test suite with ruby)
- [go](https://github.com/exercism/xgo/blob/master/.travis.yml#L10) (just uses the built-in testing tools)

Some languages are trickier than others to get running in CI. I know the lisp track is having a hell of a time getting it sorted out.

**Comment by roseaboveit** [comment]
@kytrinyx Has this issue been completely resolved?

**Comment by ricemery** [comment]
sbt test is getting run as part of the CI. So, I assume this covers the issue.

**Comment by kytrinyx** [comment]
Yepp, this looks good. Thanks!
