### ISSUE TITLE
Use Sets in sum-of-multiples?

### ISSUE THREAD

**Issue by abo64** [exercism/xscala#230]
I just had [this little discussion](http://exercism.io/submissions/f2c92a94a3d346c9bd6278fe456a0cc6).
@enricospataro may have a point here?! Shall we change the test suite?

**Comment by ErikSchierboom** [comment]
Hmmm, he has a point. The readme states: "Write a program that can find the sum of the multiples of a given **set** of numbers." Perhaps this might be a good exercise to get users to practice with sets? We could then add a hints file to help ease them into using sets.

**Comment by abo64** [comment]
I had a quick look, [in the Haskell track](http://exercism.io/exercises/haskell/sum-of-multiples/test-suite) they also use lists. So this might be something bigger.  
@ErikSchierboom But yes, we could change our test suite and add the hints.

**Comment by ErikSchierboom** [comment]
Well, the Haskell track uses lists for almost everything :)

**Comment by abo64** [comment]
@ErikSchierboom True, and that may be because only lists are directly supported in `Prelude`. :)

**Comment by enricospataro** [comment]
It also doesn't make sense to find multiples of duplicate numbers, so I think that Set is the right choice

**Comment by ricemery** [comment]
I think we should change the test suite to use a Set.. It is right there in
the Readme - "Write a program that can find the sum of the multiples of a
given set of numbers."
