### ISSUE TITLE
nth-prime: Add missing test case and change function signature

### ISSUE THREAD

**Issue by abo64** [exercism/xscala#231]
Test case ["there is no zeroth prime"](https://github.com/exercism/x-common/blob/master/exercises/nth-prime/canonical-data.json#L29) is missing in [our test suite](https://github.com/exercism/xscala/blob/master/exercises/nth-prime/src/test/scala/PrimeTest.scala).
And then it makes sense to change `Prime.nth` to return an `Option[Int]` instead of just `Int`.

While being at it: Perhaps also change all other test descriptions to be the same as in [canonical-data.json](https://github.com/exercism/x-common/blob/master/exercises/nth-prime/canonical-data.json)?

On a side note: There are more exercises out of sync with `x-common`. How can we handle this? There is an [issue on the Haskell track](https://github.com/exercism/xhaskell/issues/416) for this.

**Comment by ErikSchierboom** [comment]
I agree with all you suggestions.

As for how to make exercises sync, that's actually a hard problem. Maybe all tracks maintainers should automatically receive a notification when the canonical data of an exercise is changed?

**Comment by abo64** [comment]
Yes, that would be a good idea.
I would even say when the `description.md` changes.
And also when a new exercise is added.
