### ISSUE TITLE
Exercise dominoes still not available?

### ISSUE THREAD

**Issue by abo64** [exercism/xscala#234]
Seems like exercise `dominoes` is still not available online?
Any reasons why not?

**Comment by ErikSchierboom** [comment]
Eh, but it is? I've [submited a solution](http://exercism.io/submissions/8c41a8de287e45aba63df00aee745262). It's also in the [list of exercises](http://exercism.io/languages/scala/exercises).

**Comment by abo64** [comment]
oh right, sorry.
