### ISSUE TITLE
Upgrade to Scala 2.12 ?

### ISSUE THREAD

**Issue by abo64** [exercism/xscala#235]
Shall we upgrade to Scala 2.12, perhaps in Q1 2017 ?
This includes ScalaTest and other libraries like Monocle, of course.
A problem could be `scala-parser-combinators`?

Would be great if we find a way to simplify this for the future, ideally by just having to change only a single file?

**Comment by ErikSchierboom** [comment]
I think we should. The main argument for me is that when people search for documentation, they will be led to the latest version's documentation. Ideally, our track should match that.

Weren't the parser combinators extracted to their own library? If so, we can just add the reference to the SBT config file, right?

**Comment by ricemery** [comment]
The parser combinator dependency has already been broken out - at least in
bracket-push. I don't recall what other exercises use the the lib. But,
this was an issue I had to deal with when we moved to 2.11.

**Comment by ricemery** [comment]
What order should we change the exercises to 2.12? I am thinking we should start at the last exercise in the series and move backwards to Hello World.

**Comment by abo64** [comment]
I just saw that [parser-combinators](https://github.com/scala/scala-parser-combinators) also has a 2.12 version, so it should be smooth sailing.

@ricemery Yes, moving backwards sounds like a good strategy.

Is there a way to use variables that are read from a single source in the root directory or so? Or do we have do go through all exercises again for the next major upgrade?

**Comment by ErikSchierboom** [comment]
> Is there a way to use variables that are read from a single source in the root directory or so? Or do we have do go through all exercises again for the next major upgrade?

Unfortunately, I don't think this is possible at the moment. There is a long-standing [open issue](https://github.com/exercism/cli/issues/88) on the CLI that would add support for this feature. It would be great if someone would implement that, but I don't know any Go unfortunately. The F# and C# tracks could also really benefit for it.

**Comment by abo64** [comment]
@ricemery Just noticed that in Scala 2.12 `Either` is finally right-biased which should simplify things considerably.
So we might give the respective exercises a higher priority:
- nucleotide-count
- bowling
- forth

**Comment by ricemery** [comment]
I was just thinking about starting to porting exercises over to 2.12. I'll
start with these three.. I'll try to get started tonight if possible.

**Comment by ricemery** [comment]
TODO

- [ ] Hello World
- [ ] Bob
- [ ] Hamming
- [ ] Word Count
- [ ] Pangram
- [ ] Anagram
- [ ] Nucleotide Count
- [ ] Phone Number
- [ ] Grade School
- [ ] Robot Name
- [ ] Leap
- [ ] Etl
- [ ] Meetup
- [ ] Space Age
- [ ] Grains
- [ ] Gigasecond
- [ ] Scrabble Score
- [ ] Difference Of Squares
- [ ] Accumulate
- [ ] Sublist
- [ ] Rna Transcription
- [ ] Triangle
- [ ] Binary
- [ ] Roman Numerals
- [ ] Prime Factors
- [ ] Raindrops
- [ ] Allergies
- [ ] Atbash Cipher
- [ ] Bank Account
- [ ] Crypto Square
- [ ] Kindergarten Garden
- [ ] Robot Simulator
- [ ] Queen Attack
- [ ] Binary Search Tree
- [ ] Hexadecimal
- [ ] Largest Series Product
- [ ] Luhn
- [ ] Clock
- [ ] Matrix
- [ ] House
- [ ] Minesweeper
- [ ] Ocr Numbers
- [ ] Octal
- [ ] Trinary
- [ ] Wordy
- [ ] Food Chain
- [ ] Linked List
- [ ] Custom Set
- [ ] Nth Prime
- [ ] Palindrome Products
- [ ] Pascals Triangle
- [ ] Pig Latin
- [ ] Pythagorean Triplet
- [ ] Saddle Points
- [ ] Say
- [ ] Secret Handshake
- [ ] Series
- [ ] Sieve
- [ ] Simple Cipher
- [ ] Connect
- [ ] Parallel Letter Frequency
- [ ] SGF Parsing
- [ ] Acronym
- [ ] Zipper
- [ ] Forth
- [ ] Lens Person
- [ ] Bowling

**Comment by ricemery** [comment]
@abo64 - I submitted pull requests for Bowling and Forth. I did not see where you wanted to use the new right biased property of Either. So, I didn't do anything with that. Though, I did simplify the unit tests for Bowling.

**Comment by abo64** [comment]
@ricemery Thank you for you two PRs, they look good (+2 for `%%` in `build.sbt`). If @ErikSchierboom agrees they can be merged.

The main change will be in `nucleotide-count`: Both `example.scala` and `HINTS.md` need to be adapted.
I will create a PR for that one.

**Comment by ErikSchierboom** [comment]
@abo64 @ricemery I've looked at all three PR's and they all look great. I especially like how the bowling test suite has become significantly simpler. Great work!

**Comment by abo64** [comment]
Thanks to @ricemery !
I guess we can close this issue?

**Comment by ErikSchierboom** [comment]
That would be great! Fantastic work @ricemery

**Comment by ricemery** [comment]
Thanks @abo64 and @ErikSchierboom .

I don't think we can close this one yet. I think there are 4-5 more exercises that need to be updated that were not on the check list.

Examples - zebra-puzzle and change.

I'll add the remaining exercises to the check list. And, update them soon.

-ric

**Comment by ricemery** [comment]
Done!!!
