### ISSUE TITLE
Change test file names to match Scala convention.

### ISSUE THREAD

**Issue by stevejb71** [exercism/xscala#237]
For example, in robot-name, the filename for the spec is robot_name_test.scala.

Underscores are unusual in Scala filenames. I'd expect something like RobotNameSpec.scala.

**Comment by abo64** [comment]
You are right, these names could be changed.

The newer exercises have the naming convention to end with "Test", for example "BankAccountTest.scala" or "AllYourBaseTest.scala". So we should stick to that.

**Comment by ErikSchierboom** [comment]
Agreed, both with the PascalCase naming and the "Test" suffix.
