### ISSUE TITLE
Use an object instead of a class for some exercises

### ISSUE THREAD

**Issue by abo64** [exercism/xscala#242]
Some exercises require a `class` even though they don't have any internal state.
So they should be changed into an `object`.

- [x] allergies
- [x] atbash-cipher
- [x] crypto-square
- [x] queen-attack
- [x] raindrops

**Comment by ricemery** [comment]
@abo64 , I can work through these or a subset of them if you haven't already started.

I do think that we should also address #137 for these exercises as long as we are modifying the exercises.

**Comment by abo64** [comment]
@ricemery No, I haven't started. Please go ahead!
