### ISSUE TITLE
leap hints should mention the use of case classes

### ISSUE THREAD

**Issue by zombiefungus** [exercism/xscala#353]
This exercise is simple and in most languages the hard part would be a bunch of `if`s and some math operations, with many posible implementations. In the scala track this was solved using `case class`es but there is no way for a begginer to identify it as such, mostly because this does not exist in other languages, oposite to normal class, which you could identify as one because tests use the  `new` keyword

**Comment by zombiefungus** [comment]
Also, `case class` should be part of this exercise's topics

**Comment by abo64** [comment]
I agree, `leap` is indeed problematic.
But probably using a `case class` does not make much sense at all here - the exercise should rather be changed to use an object as we did already for some other exercises as in [this issue](https://github.com/exercism/xscala/issues/242).
So what do you think if we change the signature to something like
```scala
object LeapYear {
  def isLeapYear(year: Int): Boolean = ???
}
```
Feel free to create a PR.

If you want an additional challenge you can even add a test code generator [here](https://github.com/exercism/xscala/tree/master/testgen/src/main/scala) using [TestSuiteBuilder](https://github.com/exercism/xscala/blob/master/testgen/src/main/scala/testgen/TestSuiteBuilder.scala).

**Comment by zombiefungus** [comment]
I agree, there is no need, but changing the signature solves the problem of not introducing case classes properly just for awhile, since there are [several exercises](https://github.com/exercism/xscala/search?utf8=%E2%9C%93&q=%22case+class%22&type=) (one of them is Space Age, the next exercise to leap) that use it, but there is not even one exercise that listes it as a topic in `config.json`. When should this concept be introduced?

**Comment by abo64** [comment]
Yes, `space-age` is another exercise that could rather be a stateless object instead.

The topics are mostly taken from (not language specific) [x-common/TOPICS.txt](https://github.com/exercism/x-common/blob/master/TOPICS.txt) and AFAIK are only for internal use (for example, as a factor to determine the difficulty).
Topics should *not* be used to prescribe any solution.

**Comment by zombiefungus** [comment]
So, you suggest making both `leap` and `space-age`stateless objects, and leaving case classes for latter (whatever that implies)? The I could make a PR to help

**Comment by abo64** [comment]
In general the idea is to have classes or case classes only when some internal state makes good sense.

Great, your PRs are welcome! Please have one PR per exercise.

**Comment by zombiefungus** [comment]
Two questions:
- what should I do about `space-age`?
- do you have any example about the test generator? (something for dummies?)
thanks

**Comment by abo64** [comment]
The intention of `space-age` is to compare the age on several planets. So to set the age just once in the constructor and then to keep it as internal state could make sense. If you agree then this exercise could be kept as is?

As for the test generator. I am afraid it might be quite demanding. But this is at least to some extent b/c it is hard to come up with something that is general and flexible enough to cover all possible cases. If you try it: I am thankful for any suggestions to improve it.
Having said that a simple example is [NucleotideCountTestGenerator](https://github.com/exercism/xscala/blob/master/testgen/src/main/scala/NucleotideCountTestGenerator.scala). A more complex/customized example is [AllYourBaseTestGenerator](https://github.com/exercism/xscala/blob/master/testgen/src/main/scala/AllYourBaseTestGenerator.scala).
The input is always the respective `x-common/canonical-data.json` file.
