### ISSUE TITLE
Add way to include canonical-data.json version in generated tests

### ISSUE THREAD

**Issue by ricemery** [exercism/xscala#367]
The TestBuilder class should have a way to include the version of the canonical-data.json. The version should then be written to the generated test class as a comment. 

Possibly TestBuilder should have an `addVersion(version: String)` function to take the version value from the json. Then the TestBuilder should write something along the lines of
`// canonical-data version = 1.0.1 `
at the top of the test class.

This would make it much easier to tell if a test suite conforms to the latest canonical-data.

**Comment by abo64** [comment]
This [twirl template](https://github.com/exercism/xscala/blob/master/testgen/src/main/twirl/funSuiteTemplate.scala.txt) already includes the version (of course the exact format is debatable).
So if we decide to use [TestSuiteBuilder](https://github.com/exercism/xscala/blob/master/testgen/src/main/scala/testgen/TestSuiteBuilder.scala) the version should be there.

If we go for [TestBuilder](https://github.com/exercism/xscala/blob/master/testgen/src/main/scala/TestBuilder.scala) then the version should be included as you suggested.
(or we could use a twirl template here, too?)

**Comment by ricemery** [comment]
Nevermind.. I forgot about TestSuiteBuilder. :)
