### ISSUE TITLE
gigasecond: use times (not dates) for inputs and outputs

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xscala#51]
A duration of a gigasecond should be measured in seconds, not
days.

The `gigasecond` problem has been implemented in a number of languages,
and this issue has been generated for each of these language tracks.
This may already be fixed in this track, if so, please make a note of it
and close the issue.

There has been some discussion about whether or not gigaseconds should
take daylight savings time into account, and the conclusion was "no", since
not all locations observe daylight savings time.

**Comment by outkaj** [comment]
It seems like this can now be closed?

**Comment by ricemery** [comment]
I would think so. Back when I modified the code, I figured that @kytrinyx  would close once the issue was verified.

**Comment by kytrinyx** [comment]
I rely on people using the `Fixes #52` syntax in a commit message for closing things, as I tend to have a lot of things to process on GitHub every day, and I rarely click through to related issues unless I'm confused about the history of something.

Thanks.
