### ISSUE TITLE
Need ABOUT.md

### ISSUE THREAD

**Issue by outkaj** [exercism/xscala#88]
We need a short, friendly introduction to Scala for the website as specified [here] (http://exercism.io/languages/scala). This is especially important given overall misconceptions about Scala as a difficult language for beginners. 

The answer to the question "What types of problems does it solve really well?" should reference strong support for concurrency and parallelism.

An ABOUT.md file should be made and put into docs/. 

This is a good candidate for [24pullrequests] (http://24pullrequests.com/).

**Comment by kytrinyx** [comment]
Fixed in c976c03507abf5ef7c95a63321607b2db7e6011e
